#! usr/bin/env ruby
require_relative 'bot'
require_relative 'poster'
require 'benchmark'

bot1 = Bot.new({:name => "George", :pitch => -25})
bot2 = Bot.new({:name => "Betty", :pitch => 25})

current_bot = bot1

puts "Enable audio? (Y/n)"
response = gets.chomp.downcase

enable_audio = case response
when "y"
  true
else 
  false
end

puts "Post to Server? (Y/n)"
response = gets.chomp.downcase

post_to_heroku = case response
when "y"
  true
else 
  false
end 

initial_greeting = 'Hello'
puts "#{current_bot.name}:" + initial_greeting


if enable_audio
  current_bot.speak initial_greeting
end

reply = current_bot.send(initial_greeting)

poster = Poster.new
while true do
#  time = Benchmark.measure do
  	if current_bot == bot1 then current_bot = bot2 else current_bot = bot1 end
    content = "#{current_bot.name}: " + reply.gsub("Cleverbot", current_bot.name)
    puts content
    begin
      if post_to_heroku then poster.post_to_endpoint(content) end
    rescue Errno::ECONNREFUSED
      puts "*** Error: can't connect to rails server ***"
    end
  	if enable_audio && !reply.nil? then current_bot.speak(reply) end
    begin
  	  reply = current_bot.send(reply).gsub("kisses harder","")
    end
#  end
#  puts time
  
  
end